website:
  title: "Sidney Bissoli"
  navbar:
    left:
      - href: about.qmd
        text: About me
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: research/index.qmd
        text: Articles
  page-footer:
    center: |
      © 2025 Sidney Bissoli · Made with [Quarto](https://quarto.org/)
